workflows:
  capacitor_ios_release:
    # ... (üst kısım aynı)
    scripts:
      - name: Install dependencies
        script: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            echo "package-lock.json yok, npm install ile devam ediliyor"
            npm install --no-audit --no-fund
          fi

      - name: Build web assets
        script: |
          if npm run | grep -q " build"; then
            npm run build
          else
            echo "package.json'da build script yok, atlanıyor"
          fi

      # ⬇⬇⬇ YENİ ADIM
      - name: Ensure iOS platform exists (Capacitor)
        script: |
          # Capacitor iOS platform paketi yüklü mü?
          if ! npm ls @capacitor/ios --depth=0 >/dev/null 2>&1; then
            npm install @capacitor/ios --save-exact
          fi

          # ios klasörü yoksa ekle, varsa atla
          if [ ! -d "ios" ]; then
            echo "Capacitor iOS platformu ekleniyor..."
            npx cap add ios --skip-deps
          else
            echo "iOS platformu zaten var, devam."
          fi

      - name: Capacitor sync (iOS project)
        script: |
          # config’te appId doğru mu? (gerekirse ayarla)
          npx cap config set appId com.voiceasy.app appName "Voiceasy"
          npx cap sync ios

      - name: Install CocoaPods
        script: |
          cd ios
          pod install --repo-update

      - name: Fetch signing files (auto from App Store Connect)
        script: |
          app-store-connect fetch-signing-files \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY" \
            --type IOS_APP_STORE \
            --bundle-id "$BUNDLE_ID" \
            --create

      - name: Add certificates to keychain
        script: keychain add-certificates

      - name: Apply provisioning profiles
        script: xcode-project use-profiles --warn-only=false

      - name: Build .ipa
        script: |
          cd ios
          xcode-project build-ipa \
            --workspace "$(ls -1 *.xcworkspace | head -n 1)" \
            --scheme "$SCHEME" \
            --archive-method app-store \
            --team-id "$APPLE_TEAM_ID" \
            --bundle-id "$BUNDLE_ID"

      - name: Upload to App Store Connect (no auto-submit)
        script: |
          app-store-connect publish \
            --path "$(ls -1 build/ios/ipa/*.ipa | head -n 1)" \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY" \
            --submit-for-review=false

    artifacts:
      - build/ios/ipa/*.ipa
      - ~/Library/Developer/Xcode/Archives/**/*.xcarchive
