workflows:
  capacitor_ios_release:
    name: Voiceasy iOS (Capacitor) – Release
    instance_type: mac_mini_m1

    environment:
      groups:
        - app_store_connect   # APP_STORE_CONNECT_KEY_IDENTIFIER / APP_STORE_CONNECT_ISSUER_ID / APP_STORE_CONNECT_PRIVATE_KEY
      vars:
        APP_ID: "com.voiceasy.app"
        APP_NAME: "Voiceasy"
        APPLE_TEAM_ID: "377ECJLA2T"
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"

    scripts:
      - name: Install Node & dependencies
        script: |
          node -v || true
          npm ci || npm install

      - name: Capacitor iOS sync
        script: |
          npx cap add ios || true
          npx cap sync ios

      - name: CocoaPods install
        script: |
          cd ios/App
          pod install --repo-update

      - name: Fetch signing files (App Store + Development)
        script: |
          set -e
          keychain initialize
          # App Store (Distribution)
          app-store-connect fetch-signing-files \
            --type IOS_APP_STORE \
            --identifier "$APP_ID" \
            --create
          # Development (Debug için)
          app-store-connect fetch-signing-files \
            --type IOS_APP_DEVELOPMENT \
            --identifier "$APP_ID" \
            --create
          keychain add-certificates
          xcode-project use-profiles

      - name: Xcode archive (Release)
        script: |
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath "$CM_BUILD_DIR/Build/App.xcarchive" \
            clean archive \
            DEVELOPMENT_TEAM="$APPLE_TEAM_ID" \
            CODE_SIGN_STYLE=Automatic \
            -allowProvisioningUpdates

      - name: Create exportOptions.plist
        script: |
          cat > "$CM_BUILD_DIR/exportOptions.plist" <<'PLIST'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>signingStyle</key><string>automatic</string>
            <key>stripSwiftSymbols</key><true/>
            <key>compileBitcode</key><true/>
            <key>destination</key><string>export</string>
          </dict>
          </plist>
          PLIST

      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/Build/App.xcarchive" \
            -exportOptionsPlist "$CM_BUILD_DIR/exportOptions.plist" \
            -exportPath "$CM_BUILD_DIR/Build/ipa"

      - name: Publish to App Store Connect
        script: |
          # CLI anahtarları ENV'den alır
          app-store-connect publish \
            --path "$CM_BUILD_DIR/Build/ipa/App.ipa" \
            --bundle-id "$APP_ID"

    artifacts:
      - Build/ipa/*.ipa
      - ios/App/*.dSYM.zip
