workflows:
  capacitor_ios_release:
    name: Voiceasy iOS (Capacitor) – Release
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      xcode: 15.4
      node: 20.11.1
      vars:
        BUNDLE_ID: com.voiceasy.app
        APPLE_TEAM_ID: 377ECJLA2T
        SCHEME: App
      groups:
        - app_store_connect   # APP_STORE_CONNECT_* değişkenleri bu grupta

    scripts:
      - name: Install dependencies
        script: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            echo "package-lock.json yok, npm install ile devam ediliyor"
            npm install --no-audit --no-fund
          fi

      - name: Build web assets
        script: |
          if npm run | grep -q " build"; then
            npm run build
          else
            echo "package.json'da build script yok, atlanıyor"
          fi

      - name: Ensure iOS platform exists (Capacitor)
        script: |
          if ! npm ls @capacitor/ios --depth=0 >/dev/null 2>&1; then
            npm install @capacitor/ios --save-exact
          fi
          if [ ! -d "ios" ]; then
            echo "Capacitor iOS platformu ekleniyor..."
            npx cap add ios
          else
            echo "iOS platformu zaten var, devam."
          fi

      - name: Capacitor sync (iOS project)
        script: |
          npx cap config set appId com.voiceasy.app appName "Voiceasy"
          npx cap sync ios

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install --repo-update

      - name: Fetch signing files (auto from App Store Connect)
        script: |
          # Gerekli env kontrolü
          for v in APP_STORE_CONNECT_ISSUER_ID APP_STORE_CONNECT_KEY_IDENTIFIER APP_STORE_CONNECT_PRIVATE_KEY BUNDLE_ID; do
            if [ -z "${!v}" ]; then
              echo "ERROR: $v boş. Codemagic > Environment variables / group 'app_store_connect' kontrol edin."
              exit 1
            fi
          done

          # Sertifika için RSA private key (p12 oluştururken kullanacağız)
          openssl genrsa -out certificate_private_key.pem 2048

          # Bazı CLI sürümlerinde bundle id pozisyonel argüman
          # P12'yi PAROLASIZ üretmek için --p12-password "" veriyoruz
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY" \
            --type IOS_APP_STORE \
            --create \
            --certificate-key @file:certificate_private_key.pem \
            --p12-password ""

      - name: Add certificates to keychain
        script: |
          KEYCHAIN_PATH="$HOME/Library/Keychains/login.keychain-db"

          # Keychain kilidini aç (Codemagic login keychain genelde boş parolalıdır)
          security unlock-keychain -p "" "$KEYCHAIN_PATH" || true

          # Tüm p12'leri parolasız import et ve codesign/security erişimi ver
          for P12 in "$HOME/Library/MobileDevice/Certificates"/*.p12; do
            echo "Importing $P12"
            security import "$P12" -k "$KEYCHAIN_PATH" -P "" -T /usr/bin/codesign -T /usr/bin/security
          done

          # codesign erişimi için partition list ayarı
          security set-key-partition-list -S apple-tool:,apple: -s -k "" "$KEYCHAIN_PATH" || true

      - name: Apply provisioning profiles
        script: |
          xcode-project use-profiles --warn-only=false

      - name: Build .ipa
        script: |
          cd ios/App
          xcode-project build-ipa \
            --workspace "$(ls -1 *.xcworkspace | head -n 1)" \
            --scheme "$SCHEME" \
            --archive-method app-store \
            --team-id "$APPLE_TEAM_ID" \
            --bundle-id "$BUNDLE_ID"

      - name: Upload to App Store Connect (no auto-submit)
        script: |
          app-store-connect publish \
            --path "$(ls -1 build/ios/ipa/*.ipa | head -n 1)" \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY" \
            --submit-for-review=false

    artifacts:
      - build/ios/ipa/*.ipa
      - ~/Library/Developer/Xcode/Archives/**/*.xcarchive
